apiVersion: v1
kind: Service
metadata:
  name: python-flask-svc
  labels:
    app.kubernetes.io/name: python-microservice
    app.kubernetes.io/component: microservice
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: python-microservice
    app.kubernetes.io/component: microservice
