apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-microservice
  labels:
    app.kubernetes.io/name: python-microservice
    app.kubernetes.io/component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: python-microservice
        app.kubernetes.io/component: microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-microservice
        app.kubernetes.io/component: microservice
    spec:
      containers:
        - name: python-flask-microservice
          image: IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP